### ISSUE TITLE
Install: [Errno 16] Device or resource busy

### ISSUE THREAD

**Issue by seanhig** [contiv/install#313]
Docker Version: 17.09
CentOS 7 (1708) base
Existing docker native swarm
Remote API TLS secured on 2376
Firewalld disabled (all ports open)

Apologies if I should be posting this in the ansible project, the repo layout is a bit confusing.  I assume (hope) the same folks are working on both projects.

I am performing the install steps on the one manager node in a four node docker swarm.  Swarm is fully functional and tested.

Following the minimal, if not ambiguous, installation documentation, the installation fails in https://github.com/contiv/ansible/blob/master/roles/contiv_network/tasks/main.yml

at the step:

```
- name: setup netmaster host alias
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 netmaster"
    regexp: " netmaster$"
    state: present
  when: (run_as == "master")

```
With the error:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 16] Device or resource busy", "fatal: [node1]: FAILED! => {\"changed\": false, \"failed\": true, \"msg\": \"Unable to rename file: /tmp/tmpsgmY9l to /etc/hosts: [Errno 16] Device or resource busy\"}"`

This appears to be a known issue, updating /etc/hosts within a docker container causes this error.
https://github.com/moby/moby/issues/22281

As per the cpuguy83, editing /etc/hosts is not even supported (though there is a workaround Contiv does not employ).  Bizarre.

So I am confused.
Why would something not supported be attempted as part of the Contiv install?
Why would an error so basic come up and yet be unreported?

I must be doing something wrong, yet it doesn't seem relevant to any particular configuration item.

Help?
